### ISSUE TITLE
Demo: support for different parsers?

### ISSUE THREAD

**Issue by pierpo** [estools/esquery#107]
Hi,

I just encountered your very useful demo. Quite handy if you want to test your ESQuery queries interactively.
It works perfectly with Javascript.

However, I work with Typescript now and I'd still like to add custom ESLint rules easily.
I parse my tree using ASTExplorer https://astexplorer.net/ using different parsers, but I can't test my queries directly using the ESQuery demo.

Is there a way we can have this?

A quick win might be to be able to copy a syntax tree directly instead of code 😉

**Comment by brettz9** [comment]
I personally really like this idea. However, I think it might be better to get esquery filtering supported in ASTExplorer itself, as that already has robust options and display (I mentioned this in an offhand comment at https://github.com/fkling/astexplorer/issues/483 already, but deserves its own issue I think).

**Comment by pierpo** [comment]
Seems relevant 😊 
Thank you for your answer.

Actually, it turns out you can directly test on ASTExplorer an ESLint rule!
If you click on "Transform" above then ESLint you'll see the code for your rule and you can put your ESQuery there.

![image](https://user-images.githubusercontent.com/6313316/81271130-02f8de80-904c-11ea-9d88-d57567eb0f6f.png)


So, problem solved and nothing needs to be done 😊 

Thank you!

**Comment by karlhorky** [comment]
Thanks for the tip @pierpo ! Although I couldn't copy out of the screenshot so easily 😬

Here's a new snippet based off of the technique in the screenshot for anyone else who wants to copy + paste into AST explorer:

```js
export default function (context) {
  return {
    "JSXElement[openingElement.name.name='p'] > JSXElement[openingElement.name.name=/^span$/]": (
      node
    ) => {
      context.report({
        node,
        message: "Found"
      });
    }
  };
}
```

On AST explorer: https://astexplorer.net/#/gist/4699a2ceadc890386cbd0727734c3ca5/399b05239b34186c7cc3d659adeaa51669fcc19f

![Screenshot 2023-04-18 at 12 42 44](https://user-images.githubusercontent.com/1935696/232753990-b2a593bd-4d02-45a8-be58-2607451c80c0.png)

**Comment by brettz9** [comment]
I should note that if that is ESLint v 4, then it is a different and I believe forked version of esquery, even while it may remain mostly the same.
