### ISSUE TITLE
Array selector

### ISSUE THREAD

**Issue by jggsus88** [estools/esquery#130]
Hello,

Is there currently any way to select an element within an ArrayExpression? Something like this: 
CallExpression[callee.name='require'][arguments.0.elements]:has(value='N/algo')

**Comment by c-harding** [comment]
Given the following code:

```js
require('N/algo')
```

This selector selects the text `N/algo` in the first position in the argument list to `require`:

```css
CallExpression[callee.name='require']>.arguments:nth-child(1)[value='N/algo']
```

**Comment by jggsus88** [comment]
But what happen if I have several arguments, and I don't know the order of the one I'm searching for. For example, with this code:
`requite('N/one', 'N/two', 'N/three')`
What happen if I want to select 'N/two', but I don't know its position within the list of arguments?

**Comment by c-harding** [comment]
Just drop the `:nth-child(1)`, making sure there is no space between `.arguments` and `[value=…]`. It seems slightly counterintuitive at first, but the `.arguments` is actually like a CSS class on each of the direct children of the CallExpression.

**Comment by jggsus88** [comment]
Thank you for your response, that works. But what I actually need is to select an element within an array that is an argument of a CallExpression. I supposed that should be something like this: `CallExpression[callee.name='require']>.arguments.0.elements[value='N/one']`
But it's not working for the following code:
`require(["N/one", "N/two"]);`
Any ideas?

**Comment by c-harding** [comment]
How specific does it have to be? This will match your string nested anywhere within the arguments

```css
CallExpression[callee.name='require'] Literal[value='N/one']
```

**Comment by c-harding** [comment]
Otherwise, this will match only an array given as the first argument, containing your string literal in any position:

```css
CallExpression[callee.name='require']
> ArrayExpression.arguments:first-child
> Literal.elements[value='N/one']
```

**Comment by jggsus88** [comment]
That work's!! Thank you so much.
