### ISSUE TITLE
Help with array null child selector

### ISSUE THREAD

**Issue by mariaines** [estools/esquery#143]
Hi there,

I'm trying to write a selector to match an array where the first child is null. [This issue](https://github.com/estools/esquery/issues/130) showed me how to select the first child, but how do I match against a null element when there are no fields to check? I hope this is possible 🤞🏽

Specifically I'm trying to match against:
```jsx
const [, actions] = ...
```

I can get this to work: `"VariableDeclaration[kind=const] > VariableDeclarator[id.type=ArrayPattern] > ArrayPattern[elements.length=2] >.elements:nth-child(1)[name=someName]"` against:
```jsx
const [someName, actions] = ...
```

**Comment by michaelficarra** [comment]
You mean something like this?

```css
VariableDeclaration[kind=const] > VariableDeclarator[id.type=ArrayPattern] > ArrayPattern[elements.0=null]
```

**Comment by mariaines** [comment]
Yes, that does it! Please forgive the noob question 🙂 Thank you so much @michaelficarra !

**Comment by michaelficarra** [comment]
No worries, happy I could help.
