### ISSUE TITLE
npm out of date

### ISSUE THREAD

**Issue by kumavis** [estools/esquery#47]
https://www.npmjs.com/package/esquery

is out of date
e.g.: missing the 'class' type selector

here's the changes since last publish https://github.com/estools/esquery/compare/e81ac4686f3d7142b920c475b05d2c670916bd5c...master
> Showing  38 changed files  with 1,665 additions and 2,290 deletions.

**Comment by kumavis** [comment]
@jrfeenst can you add some collaborators on npm? @michaelficarra and/or myself

**Comment by jrfeenst** [comment]
Add @michaelficarra to npm collaborators list.

**Comment by kumavis** [comment]
cheers :beers: 
@michaelficarra care to do the honors?

**Comment by michaelficarra** [comment]
Published `0.4.0`.
