### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by mroger** [estools/esquery#51]
Hi,

I'm trying to run the tests with the command:

`npm test`

results in error for me:

`Error: Tried loading "fixtures/conditional" at ./fixtures/conditional.js then tried...`

But when I run with the command below, the tests run ok:

`node node_modules/jstestr/bin/jstestr.js module=tests/queryAttribute`
`node node_modules/jstestr/bin/jstestr.js module=tests/queryField`
`etc...`

 Is there some other command I have to use?

I´m running with:

- Windows 10
- Node v6.9.1
- npm 3.10.8

Thank you.

**Comment by brettz9** [comment]
There's a different testing framework now anyways, so I think this could be closed (unless you wanted to try again to make sure).
