### ISSUE TITLE
TSQuery!

### ISSUE THREAD

**Issue by phenomnomnominal** [estools/esquery#66]
Hey team!

I've been using ESQuery for several years and I love the API, so thank you for your efforts. I've been writing a lot of TypeScript lately, and I've had a go at a project using the ESQuery API for querying TypeScript ASTs. I'm planning on open-sourcing it, but I checked out your licence and saw the following point:

> Neither the name of the ESQuery nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

I'm hoping it will be okay to mention that the API is taken from ESQuery (and that it uses your selector parser internally)? Assuming that falls within the realm of that particular licence term, I'd like to request permission to use the name ESQuery.

Thanks!

**Comment by michaelficarra** [comment]
This is standard wording in a 3-clause BSD license. My understanding (I am not a lawyer) of this statement is that it is intended to prevent someone from advertising that a product either

1. uses all/part of a BSD-licensed project, or
1. contains code from one of the contributors of a BSD-licensed project

with the intention of promoting that product. Saying something factual like how the API is largely derived from the esquery API is neither an endorsement nor a promotion. I'm pretty sure you're good here.

Also, if you're looking for written permission to violate the terms of this license, you're probably going to have to get that written permission from each of the contributors who still have code in `master`. That's no small task, and in my opinion not worth the effort at all.

Lastly, that sounds like a cool project. Be sure to link it here when you're done.

**Comment by phenomnomnominal** [comment]
Awesome, thanks for clarifying that - I think you're right, and I certainly don't intend to violate the clause, so hopefully we are all good! Probably all good to close this?

Code is [here](https://github.com/phenomnomnominal/tsquery), still a WIP but mostly functional (with a few tests needing to be implemented).
