### ISSUE TITLE
Update gh-pages

### ISSUE THREAD

**Issue by brettz9** [estools/esquery#79]
Could you update gh-pages so that https://estools.github.io/esquery/ is against the current version, or, better yet, use Github's ability under Settings to have the github.io URL point to `master` so it is always up to date?

Thanks!

**Comment by michaelficarra** [comment]
@brettz9 I'd prefer to keep the demo page out of master. You can send a PR to `gh-pages` with the updates if you like.

**Comment by michaelficarra** [comment]
Closed by https://github.com/estools/esquery/pull/86#issuecomment-602378430.
