### ISSUE TITLE
There has a loop when query unknown key JSXOpeningElement.

### ISSUE THREAD

**Issue by uni-zheng** [estools/esquery#99]
I use ESLint with babel-eslint parser to check my code. There has a loop when query unknown key JSXOpeningElement.

I made a pr in estraverse. But esquery resolve this issue maybe  better.

https://github.com/estools/estraverse/pull/107#issuecomment-611302763

**Comment by michaelficarra** [comment]
No thanks, estraverse is the correct place for this.
